export const ADMIN_HANDLER = "ADMIN_HANDLER";
export const RESET_USER = "RESET_USER";
export const GET_USERS_LOGED = "GET_USERS_LOGED";
export const GET_USER_DB = "GET_USER_DB";
export const SET_LOADING = "SET_LOADING";
export const SET_USER = "SET_USER";
export const CREATE_USER = "CREATE_USER";
export const SET_FAV = "SET_FAV";
export const UPDATE_USER = "UPDATE_USER";
export const RESET_USER_DB = "RESET_USER_DB";
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID"; //por id
export const FILTER_BY_BRAND = "FILTER_BY_BRAND"; //por marcas
export const FILTER_BY_TYPE = "FILTER_BY_TYPE"; // tipo de bebida
export const FILTER_BY_GRADUATION = "FILTER_BY_GRADUATION"; // GRADO de graduacion
export const FILTER_BY_ML = "FILTER_BY_ML";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE"; // precio
export const FILTER_BY_AZ = "FILTER_BY_AZ"; // alfabetico
export const GET_BRANDS = "GET_BRANDS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_CARRITO = "ADD_CARRITO";
export const ADD_IN_CART = "ADD_IN_CART";
export const DELETE_ONE_PRODUCT = "DELETE_ONE_PRODUCT";
export const REMOVE_ALL_CARRITO = "REMOVE_ALL_CARRITO";
export const BUY_ALL_CART = "BUY_ALL_CART"; // esperando ruta
export const GET_MERCADO_PAGO = "GET_MERCADO_PAGO";
export const ORDER_MERCADO_PAGO = "ORDER_MERCADO_PAGO"; // recibe la orden del carrito y la lleva a MP
export const DELETE_MERCADO_PAGO = "DELETE_MERCADO_PAGO";
export const FEEDBACK_MERCADO_PAGO = "FEEDBACK_MERCADO_PAGO";
export const POST_REVIEW = "POST_REVIEW";
export const GET_REVIEW = "GET_REVIEW";
export const PUT_REVIEW = "PUT_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const GET_FAV = "GET_FAV";
export const DEL_FAV = "DEL_FAV";
export const GET_REVPAGE = "GET_REVPAGE";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const GET_DIRECCIONES = "GET_DIRECCIONES";
export const ADD_DIRECCIONES = "ADD_DIRECCIONES";
export const DELETE_DIRECCIONES = "DELETE_DIRECCIONES";
export const ADD_HIST = "ADD_HIST";
export const GET_HIST = "GET_HIST";
export const CLEAR_STATE = "CLEAR_STATE";
export const PUT_PRODUCTO = "PUT_PRODUCTO";
export const GET_REVIEW_BY_USER = "GET_REVIEW_BY_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const FIND_REVIEW_ID = "FIND_REVIEW_ID";
export const FILTER_USER_REVIEW = "FILTER_USER_REVIEW"
export const GET_STATS = "GET_STATS"
export const GET_TOP_PRODS = "GET_TOP_PRODS"
